//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly_On_Time.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fly_On_Time.Utilities.ApiKeys", typeof(ApiKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 745e3a7b.
        /// </summary>
        internal static string fsAppID {
            get {
                return ResourceManager.GetString("fsAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cba6680ba0187670fc07b04f0ee3b57d.
        /// </summary>
        internal static string fsAppKey {
            get {
                return ResourceManager.GetString("fsAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/.
        /// </summary>
        internal static string fsDelayIndex {
            get {
                return ResourceManager.GetString("fsDelayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.flightstats.com/flex/flightstatus/rest/v2/json/flight/status/.
        /// </summary>
        internal static string fsFlightStatusByArrivalDate {
            get {
                return ResourceManager.GetString("fsFlightStatusByArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.flightstats.com/flex/schedules/rest/v1/json/flight/.
        /// </summary>
        internal static string fsScheduledFlightsByCarrierFNDate {
            get {
                return ResourceManager.GetString("fsScheduledFlightsByCarrierFNDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.flightstats.com/flex/weather/rest/v1/json/metar/.
        /// </summary>
        internal static string fsWeather {
            get {
                return ResourceManager.GetString("fsWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyDSPU5jM6i4BxPw0SYq5JOqq6JbmzW6mcA.
        /// </summary>
        internal static string googleCurLocationKey {
            get {
                return ResourceManager.GetString("googleCurLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyBf3CLng_I7aSdXXBEIJZJEf3_WNK7patA.
        /// </summary>
        internal static string googleMapsAppKey {
            get {
                return ResourceManager.GetString("googleMapsAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maps.googleapis.com.
        /// </summary>
        internal static string googleMapsAppURL {
            get {
                return ResourceManager.GetString("googleMapsAppURL", resourceCulture);
            }
        }
    }
}
